package view;

public enum View {
	MAIN,					// 기본화면
	ADMIN,
	LOGIN,
	ACCOUNT_CREATE,
	MEMBER_SIGNUP,
	ACCOUNT_LIST,
	ACCOUNT_INFO,
	DEPOSIT_INFO,
	WITHDRAW_INFO,
	DEPOWITH_INFO,
	DEPOWITH, DEPOSIT, WITHDRAW, TRANSFER, ACCOUNT_DETAIL

}
